distance_vectorial_to_plane_R16P – VecFor
distance_vectorial_to_plane_R16P Function
10 statements
Source File
public elemental function distance_vectorial_to_plane_R16P(self, pt1, pt2, pt3) result(distance)
Calculate the distance (vectorial) to plane defined by the 3 points.
The convention for the points numeration is the following:
 3.----.2
   \   |
    \ *---------> . self
     \ |
      \|
       .1
 type(vector_R16P) :: pt(0:3)
 pt(0) = 5.3 * ez_R16P
 pt(1) = ex_R16P
 pt(2) = ey_R16P
 pt(3) = ex_R16P - ey_R16P
 pt(0) = pt(0)%distance_vectorial_to_plane(pt1=pt(1), pt2=pt(2), pt3=pt(3))
 print "(3(F3.1,1X))", pt(0)%x, pt(0)%y, pt(0)%z
 type(vector_R16P) :: pt(0:3)
 pt(0) = 5.3 * ez_R16P
 pt(1) = ex_R16P
 pt(2) = ey_R16P
 pt(3) = ex_R16P - ey_R16P
 pt(0) = distance_vectorial_to_plane_R16P(pt(0), pt1=pt(1), pt2=pt(2), pt3=pt(3))
 print "(3(F3.1,1X))", pt(0)%x, pt(0)%y, pt(0)%z
Arguments
Type Intent Optional Attributes Name
class(vector_R16P), intent(in) :: self
The point from which computing the distance.
type(vector_R16P), intent(in) :: pt1
First plane point.
type(vector_R16P), intent(in) :: pt2
Second plane point.
type(vector_R16P), intent(in) :: pt3
Third plane point.
Return Value type(vector_R16P)
Face normal.
Calls
Called by
Contents
None
Call graph
distance_vectorial_to_plane_r16p calls face_normal3_r16p
face_normal3_r16p calls normalized_r16p
volatile_doctest calls distance_vectorial_to_plane_r16p