face_normal3_R16P – VecFor
face_normal3_R16P Function
16 statements
Source File
public elemental function face_normal3_R16P(pt1, pt2, pt3, norm) result(normal)
Calculate the normal of the face defined by the 3 points.
The convention for the points numeration is the following:
 3.----.2
   \   |
    \  |
     \ |
      \|
       .1
The normal is calculated by the cross product of the side s12 for the side s13: s12 x s13. The normal is normalized if the variable norm is passed (with any value).
 type(vector_R16P) :: pt(0:3)
 pt(1) = ex_R16P
 pt(2) = ey_R16P
 pt(3) = ex_R16P - ey_R16P
 pt(0) = pt(1)%face_normal3(pt1=pt(1), pt2=pt(2), pt3=pt(3), norm='y')
 print "(3(F3.1,1X))", abs(pt(0)%x), abs(pt(0)%y), abs(pt(0)%z)
 type(vector_R16P) :: pt(0:3)
 pt(1) = ex_R16P
 pt(2) = ey_R16P
 pt(3) = ex_R16P - ey_R16P
 pt(0) = face_normal3_R16P(pt1=pt(1), pt2=pt(2), pt3=pt(3), norm='y')
 print "(3(F3.1,1X))", abs(pt(0)%x), abs(pt(0)%y), abs(pt(0)%z)
Arguments
Type Intent Optional Attributes Name
type(vector_R16P), intent(in) :: pt1
First face point.
type(vector_R16P), intent(in) :: pt2
Second face point.
type(vector_R16P), intent(in) :: pt3
Third face point.
character(len=1), intent(in), optional :: norm
If ‘norm’ is passed as argument the normal is normalized.
Return Value type(vector_R16P)
Face normal.
Calls
Called by
Contents
None
Call graph
face_normal3_r16p calls normalized_r16p
distance_to_plane_r16p calls face_normal3_r16p
distance_vectorial_to_plane_r16p calls face_normal3_r16p
volatile_doctest calls face_normal3_r16p, distance_to_plane_r16p, distance_vectorial_to_plane_r16p