normL2_R16P – VecFor
normL2_R16P Function
5 statements
Source File
public elemental function normL2_R16P(self) result(norm)
Return the norm L2 of vector.
The norm L2 if defined as .
 type(vector_R16P) :: pt
 pt = ex_R16P + ey_R16P
 print "(F4.2)", pt%normL2()
 type(vector_R16P) :: pt
 pt = ex_R16P + ey_R16P
 print "(F4.2)", normL2_R16P(pt)
Arguments
Type Intent Optional Attributes Name
class(vector_R16P), intent(in) :: self
Vector.
Return Value real(kind=R16P)
Norm L2.
Called by
Contents
None
Call graph
i1p_not_eq_vector calls norml2_r16p
r16p_great_vector calls norml2_r16p
vector_low_r8p calls norml2_r16p
r4p_low_vector calls norml2_r16p
vector_great_i2p calls norml2_r16p
i8p_great_eq_vector calls norml2_r16p
r8p_not_eq_vector calls norml2_r16p
parallel calls norml2_r16p
vector_great_eq_r4p calls norml2_r16p
vector_not_eq_r16p calls norml2_r16p
r16p_low_eq_vector calls norml2_r16p
vector_low_eq_i1p calls norml2_r16p
normalize calls norml2_r16p
i4p_eq_vector calls norml2_r16p
vector_great_i4p calls norml2_r16p
i8p_great_vector calls norml2_r16p
vector_great_eq_r8p calls norml2_r16p
vector_not_eq_r4p calls norml2_r16p
r16p_low_vector calls norml2_r16p
vector_eq_i1p calls norml2_r16p
vector_low_eq_i2p calls norml2_r16p
i4p_great_eq_vector calls norml2_r16p
r4p_not_eq_vector calls norml2_r16p
vector_great_i8p calls norml2_r16p
i8p_low_eq_vector calls norml2_r16p
vector_great_eq_vector calls norml2_r16p
vector_not_eq_r8p calls norml2_r16p
i2p_eq_vector calls norml2_r16p
vector_eq_i2p calls norml2_r16p
vector_low_eq_i4p calls norml2_r16p
i4p_great_vector calls norml2_r16p
vector_great_r16p calls norml2_r16p
volatile_doctest calls norml2_r16p, angle_r16p, distance_to_line_r16p
i1p_eq_vector calls norml2_r16p
i8p_low_vector calls norml2_r16p
angle_r16p calls norml2_r16p
vector_great_vector calls norml2_r16p
vector_not_eq_vector calls norml2_r16p
i2p_great_eq_vector calls norml2_r16p
r16p_not_eq_vector calls norml2_r16p
vector_eq_i4p calls norml2_r16p
vector_low_eq_i8p calls norml2_r16p
i4p_low_eq_vector calls norml2_r16p
vector_great_r4p calls norml2_r16p
i1p_great_eq_vector calls norml2_r16p
vector_low_i1p calls norml2_r16p
i2p_great_vector calls norml2_r16p
vector_eq_i8p calls norml2_r16p
vector_low_eq_r16p calls norml2_r16p
i4p_low_vector calls norml2_r16p
r8p_eq_vector calls norml2_r16p
vector_great_r8p calls norml2_r16p
i8p_not_eq_vector calls norml2_r16p
distance_to_line_r16p calls norml2_r16p
vector_low_i2p calls norml2_r16p
i2p_low_eq_vector calls norml2_r16p
vector_eq_r16p calls norml2_r16p
vector_low_eq_r4p calls norml2_r16p
r8p_great_eq_vector calls norml2_r16p
vector_great_eq_i1p calls norml2_r16p
i1p_great_vector calls norml2_r16p
vector_low_i4p calls norml2_r16p
i2p_low_vector calls norml2_r16p
r4p_eq_vector calls norml2_r16p
vector_eq_r4p calls norml2_r16p
vector_low_eq_r8p calls norml2_r16p
i4p_not_eq_vector calls norml2_r16p
r8p_great_vector calls norml2_r16p
vector_great_eq_i2p calls norml2_r16p
vector_not_eq_i1p calls norml2_r16p
i1p_low_eq_vector calls norml2_r16p
vector_low_i8p calls norml2_r16p
r4p_great_eq_vector calls norml2_r16p
vector_eq_r8p calls norml2_r16p
vector_low_eq_vector calls norml2_r16p
r8p_low_eq_vector calls norml2_r16p
vector_great_eq_i4p calls norml2_r16p
vector_not_eq_i2p calls norml2_r16p
i1p_low_vector calls norml2_r16p
r16p_eq_vector calls norml2_r16p
vector_low_r16p calls norml2_r16p
i2p_not_eq_vector calls norml2_r16p
r4p_great_vector calls norml2_r16p
vector_eq_vector calls norml2_r16p
vector_low_vector calls norml2_r16p
r8p_low_vector calls norml2_r16p
vector_great_eq_i8p calls norml2_r16p
vector_not_eq_i4p calls norml2_r16p
r16p_great_eq_vector calls norml2_r16p
vector_low_r4p calls norml2_r16p
r4p_low_eq_vector calls norml2_r16p
vector_great_i1p calls norml2_r16p
i8p_eq_vector calls norml2_r16p
vector_great_eq_r16p calls norml2_r16p
vector_not_eq_i8p calls norml2_r16p