normalized – VecFor
normalized Function
6 statements
Source File
public elemental function normalized(self) result(norm)
Return a normalized copy of vector.
The normalization is made by means of norm L2. If the norm L2 of the vector is less than the parameter smallRPP the normalization value is set to normL2(vec)+smallRPP.
 type(vector) :: pt
 pt = ex + ey
 pt = pt%normalized()
 print "(3(F4.2,1X))", abs(pt%x), abs(pt%y), abs(pt%z)
 type(vector) :: pt
 pt = ex + ey
 pt = normalized(pt)
 print "(3(F4.2,1X))", abs(pt%x), abs(pt%y), abs(pt%z)
Arguments
Type Intent Optional Attributes Name
class(vector), intent(in) :: self
Vector.
Return Value type(vector)
Normalized copy.
Called by
Contents
None
Call graph
mirror_matrix calls normalized
vector_eq_vector calls normalized
rotation_matrix calls normalized
vector_not_eq_vector calls normalized
face_normal4 calls normalized
volatile_doctest calls normalized, face_normal3, face_normal4, distance_vectorial_to_plane, distance_to_plane
face_normal3 calls normalized
parallel calls normalized
rotate_by_axis_angle calls rotation_matrix
distance_vectorial_to_plane calls face_normal3
mirror_by_normal calls mirror_matrix
distance_to_plane calls face_normal3