normalized_R16P – VecFor
normalized_R16P Function
6 statements
Source File
public elemental function normalized_R16P(self) result(norm)
Return a normalized copy of vector.
The normalization is made by means of norm L2. If the norm L2 of the vector is less than the parameter smallRPP the normalization value is set to normL2(vec)+smallRPP.
 type(vector_R16P) :: pt
 pt = ex_R16P + ey_R16P
 pt = pt%normalized()
 print "(3(F4.2,1X))", abs(pt%x), abs(pt%y), abs(pt%z)
 type(vector_R16P) :: pt
 pt = ex_R16P + ey_R16P
 pt = normalized_R16P(pt)
 print "(3(F4.2,1X))", abs(pt%x), abs(pt%y), abs(pt%z)
Arguments
Type Intent Optional Attributes Name
class(vector_R16P), intent(in) :: self
Vector.
Return Value type(vector_R16P)
Normalized copy.
Called by
Contents
None
Call graph
face_normal3_r16p calls normalized_r16p
parallel calls normalized_r16p
volatile_doctest calls normalized_r16p, face_normal3_r16p, face_normal4_r16p, distance_to_plane_r16p, distance_vectorial_to_plane_r16p
face_normal4_r16p calls normalized_r16p
mirror_matrix_r16p calls normalized_r16p
rotation_matrix_r16p calls normalized_r16p
vector_eq_vector calls normalized_r16p
vector_not_eq_vector calls normalized_r16p
distance_to_plane_r16p calls face_normal3_r16p
mirror_by_normal calls mirror_matrix_r16p
distance_vectorial_to_plane_r16p calls face_normal3_r16p
rotate_by_axis_angle calls rotation_matrix_r16p