normalized_R8P – VecFor
normalized_R8P Function
6 statements
Source File
public elemental function normalized_R8P(self) result(norm)
Return a normalized copy of vector.
The normalization is made by means of norm L2. If the norm L2 of the vector is less than the parameter smallRPP the normalization value is set to normL2(vec)+smallRPP.
 type(vector_R8P) :: pt
 pt = ex_R8P + ey_R8P
 pt = pt%normalized()
 print "(3(F4.2,1X))", abs(pt%x), abs(pt%y), abs(pt%z)
 type(vector_R8P) :: pt
 pt = ex_R8P + ey_R8P
 pt = normalized_R8P(pt)
 print "(3(F4.2,1X))", abs(pt%x), abs(pt%y), abs(pt%z)
Arguments
Type Intent Optional Attributes Name
class(vector_R8P), intent(in) :: self
Vector.
Return Value type(vector_R8P)
Normalized copy.
Called by
Contents
None
Call graph
face_normal4_r8p calls normalized_r8p
mirror_matrix_r8p calls normalized_r8p
rotation_matrix_r8p calls normalized_r8p
vector_not_eq_vector calls normalized_r8p
vector_eq_vector calls normalized_r8p
face_normal3_r8p calls normalized_r8p
parallel calls normalized_r8p
volatile_doctest calls normalized_r8p, face_normal4_r8p, face_normal3_r8p, distance_vectorial_to_plane_r8p, distance_to_plane_r8p
distance_vectorial_to_plane_r8p calls face_normal3_r8p
rotate_by_axis_angle calls rotation_matrix_r8p
distance_to_plane_r8p calls face_normal3_r8p
mirror_by_normal calls mirror_matrix_r8p