printf – VecFor
printf Subroutine
27 statements
Source File
private subroutine printf(self, unit, prefix, sep, suffix, iostat, iomsg)
Print in a pretty ascii format the components of type Vector.
 type(vector) :: pt
 pt = ex + ey
 call pt%printf(prefix='[x, y, z] = ', sep=', ')
Arguments
Type Intent Optional Attributes Name
class(vector), intent(in) :: self
Vector.
integer(kind=I4P), intent(in), optional :: unit
Logic unit.
character, intent(in), optional :: prefix
Prefix string.
character, intent(in), optional :: sep
Components separator.
character, intent(in), optional :: suffix
Suffix string.
integer(kind=I4P), intent(out), optional :: iostat
IO error.
character, intent(out), optional :: iomsg
IO error message.
Calls
Contents
None
Call graph
printf calls str
str calls strf_r8p, str_i1p, str_a_r4p, str_i2p, str_i8p, str_a_i2p, str_r8p, str_bol, str_r4p, str_i4p, str_a_i8p, strf_i4p, strf_i1p, str_a_i1p, strf_r4p, str_a_r8p, strf_i8p, strf_i2p, str_a_i4p
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_r8p calls compact_real_string
str_r4p calls compact_real_string
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_a_i4p calls str_i4p