strf_I2P – VecFor
strf_I2P Function
6 statements
Source File
private elemental function strf_I2P(fm, n) result(str)
Convert integer to string.
 use penf
 print "(A)", str(fm=FI2P, n=1_I2P)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I2P), intent(in) :: n
Integer to be converted.
Return Value character
Returned string containing input number.
Called by
Contents
Source Code
strf_I2P
Source Code
   elemental function strf_I2P(fm, n) result(str)
   !< Convert integer to string.
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(fm=FI2P, n=1_I2P)
   !<```
   !=> 1 <<<
   character(*), intent(in) :: fm  !< Format different from the standard for the kind.
   integer(I2P), intent(in) :: n   !< Integer to be converted.
   character(DI2P)          :: str !< Returned string containing input number.
   write(str, trim(fm)) n
   endfunction strf_I2P
Call graph
str calls strf_i2p
printf calls str
bctoi_i8p calls str
bctoi_i2p calls str
volatile_doctest calls str
bctoi_i1p calls str
bctoi_i4p calls str
bcton calls bctoi_i8p, bctoi_i2p, bctoi_i1p, bctoi_i4p