volatile_doctest – VecFor
volatile_doctest Program
6 statements
Source File
Uses
penf
vecfor_RPP
Calls
Contents
Variables
pt
Source Code
volatile_doctest
Variables
Type Attributes Name Initial
type(vector) :: pt
Source Code
program volatile_doctest
use vecfor_RPP
 use penf, only : byte_size
 type(vector) :: pt
 print*, iolen(pt)/byte_size(pt%x)
endprogram volatile_doctest
Call graph
volatile_doctest calls iolen, byte_size
byte_size calls byte_size_i4p, byte_size_i1p, byte_size_r8p, byte_size_i2p, byte_size_i8p, byte_size_r4p, byte_size_chr