volatile_doctest – VecFor
volatile_doctest Program
6 statements
Source File
Uses
penf
vecfor_R8P
Calls
Contents
Variables
pt
Source Code
volatile_doctest
Variables
Type Attributes Name Initial
type(vector_R8P) :: pt
Source Code
program volatile_doctest
use vecfor_R8P
 use penf, only : byte_size
 type(vector_R8P) :: pt
 print*, iolen_R8P(pt)/byte_size(pt%x)
endprogram volatile_doctest
Call graph
volatile_doctest calls iolen_r8p, byte_size
byte_size calls byte_size_i8p, byte_size_i2p, byte_size_chr, byte_size_r4p, byte_size_r8p, byte_size_i4p, byte_size_i1p