volatile_doctest – VecFor
volatile_doctest Program
11 statements
Source File
Uses
vecfor_R16P
Calls
Contents
Variables
pt res
Source Code
volatile_doctest
Variables
Type Attributes Name Initial
type(vector_R16P) :: pt(0:1)
character(len=4) :: res(3)
Source Code
program volatile_doctest
use vecfor_R16P
 type(vector_R16P) :: pt(0:1)
 character(4) :: res(3)
 pt(1) = 1 * ex_R16P + 2 * ey_R16P + 1 * ez_R16P
 pt(0) = pt(1) - 2_I8P
 res(1) = trim(adjustl(str('(F4.1)',pt(0)%x)))
 res(2) = trim(adjustl(str('(F4.1)',pt(0)%y)))
 res(3) = trim(adjustl(str('(F4.1)',pt(0)%z)))
 print "(A4,1X,A3,1X,A4)", res(1), res(2), res(3)
endprogram volatile_doctest
Call graph
volatile_doctest calls str
str calls strf_i1p, str_a_i1p, str_i8p, str_a_r8p, str_r8p, strf_i2p, str_a_i4p, str_r4p, str_i1p, strf_i4p, str_a_r4p, strf_r4p, str_i2p, str_a_i2p, strf_i8p, str_bol, strf_r8p, str_i4p, str_a_i8p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_r8p calls compact_real_string
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p